import { badRequest } from './http.js';

/**
 * Query-parameter reading and validation.
 *
 * Every value that reaches this module is attacker-controlled. The rules are:
 * bound the length of anything free-text before it is used, reject rather than
 * coerce anything that claims to be a number, and clamp paging to a range the
 * function can always serve. Nothing here is ever compiled into a RegExp or
 * passed to anything evaluated — matching is done with `String.includes` in the
 * shared scoring module.
 */

/** Free-text cap. Long enough for a real query, short enough to bound scoring. */
export const MAX_QUERY_LENGTH = 120;

/** Country names are short; anything longer is not a country. */
const MAX_COUNTRY_LENGTH = 80;

/** Company ids are slugs generated by the update script. */
const MAX_ID_LENGTH = 64;

export const REMOTE_POLICIES = ['remote', 'hybrid', 'onsite'] as const;
export type RemotePolicyParam = (typeof REMOTE_POLICIES)[number];

/**
 * Read the first present alias of a free-text param.
 * Returns null for absent or blank values so callers can treat "not filtering"
 * and "filtering on nothing" identically.
 */
export function readText(
  url: URL,
  names: readonly string[],
  maxLength: number,
): string | null {
  for (const name of names) {
    const raw = url.searchParams.get(name);
    if (raw === null) continue;

    const value = raw.trim();
    if (value.length === 0) return null;

    if (value.length > maxLength) {
      throw badRequest(
        `"${name}" must be ${maxLength} characters or fewer (received ${value.length}).`,
      );
    }
    return value;
  }
  return null;
}

export function readKeyword(url: URL, names: readonly string[]): string | null {
  return readText(url, names, MAX_QUERY_LENGTH);
}

export function readCountry(url: URL, names: readonly string[]): string | null {
  return readText(url, names, MAX_COUNTRY_LENGTH);
}

export function readRemotePolicy(url: URL): RemotePolicyParam | null {
  const value = readText(url, ['remote'], 16);
  if (value === null) return null;

  const normalized = value.toLowerCase();
  const match = REMOTE_POLICIES.find((policy) => policy === normalized);
  if (match === undefined) {
    throw badRequest(`"remote" must be one of: ${REMOTE_POLICIES.join(', ')}.`);
  }
  return match;
}

/**
 * Read a size bound. Unlike paging, a malformed size is rejected rather than
 * ignored: silently dropping `minSize=fifty` would return the unfiltered list
 * and the caller would never know its filter did nothing.
 */
export function readSizeBound(url: URL, name: string): number | null {
  const raw = url.searchParams.get(name);
  if (raw === null) return null;

  const value = raw.trim();
  if (value.length === 0) return null;

  const parsed = Number(value);
  if (!Number.isFinite(parsed) || !Number.isInteger(parsed) || parsed < 0) {
    throw badRequest(`"${name}" must be a non-negative integer (received "${value}").`);
  }
  if (parsed > Number.MAX_SAFE_INTEGER) {
    throw badRequest(`"${name}" is out of range.`);
  }
  return parsed;
}

/** Paging is clamped, never rejected — a nonsense page is a harmless no-op. */
export function readClampedInt(
  url: URL,
  name: string,
  fallback: number,
  min: number,
  max: number,
): number {
  const raw = url.searchParams.get(name);
  if (raw === null || raw.trim().length === 0) return fallback;

  const parsed = Number(raw);
  if (!Number.isFinite(parsed)) return fallback;

  return Math.min(max, Math.max(min, Math.trunc(parsed)));
}

export interface Paging {
  readonly limit: number;
  readonly offset: number;
}

export function readPaging(url: URL, defaultLimit: number, maxLimit: number): Paging {
  return {
    limit: readClampedInt(url, 'limit', defaultLimit, 1, maxLimit),
    offset: readClampedInt(url, 'offset', 0, 0, Number.MAX_SAFE_INTEGER),
  };
}

/**
 * Pull the trailing path segment of a dynamic route. Vercel's Web Handler
 * signature does not hand the function its matched params, so the id comes
 * from the URL — and is length-checked before it is used as a map key.
 */
export function readIdFromPath(url: URL): string {
  const segments = url.pathname.split('/').filter((segment) => segment.length > 0);
  const last = segments[segments.length - 1];

  if (last === undefined || last === 'companies') {
    throw badRequest('A company id is required: /api/companies/{id}.');
  }

  let decoded: string;
  try {
    decoded = decodeURIComponent(last);
  } catch {
    throw badRequest('The company id is not valid URL-encoded text.');
  }

  if (decoded.length > MAX_ID_LENGTH) {
    throw badRequest(`Company ids are at most ${MAX_ID_LENGTH} characters.`);
  }
  return decoded;
}
