#!/usr/bin/env node
/**
 * Regenerates src/lib/regions.ts from the same Intl data the pipeline uses to
 * write country names. Run it after changing a region list below:
 *
 *   node scripts/update/gen-regions.mjs
 */
import { writeFileSync } from 'node:fs';
import { fromCode } from './lib/countries.mjs';

const codes = (s) => s.split(/\s+/).filter(Boolean);
const EUROPE = codes('AL AD AT BY BE BA BG HR CY CZ DK EE FI FR DE GR HU IS IE IT XK LV LI LT LU MT MD MC ME NL MK NO PL PT RO SM RS SK SI ES SE CH UA GB VA');
const MIDDLE_EAST = codes('AE BH EG IL IQ IR JO KW LB OM PS QA SA SY TR YE CY');
const AFRICA = codes('DZ AO BJ BW BF BI CV CM CF TD KM CG CD CI DJ EG GQ ER SZ ET GA GM GH GN GW KE LS LR LY MG MW ML MR MU MA MZ NA NE NG RW ST SN SC SL SO ZA SS SD TZ TG TN UG ZM ZW');
const NORTH_AMERICA = codes('US CA MX');
const CARIBBEAN_CENTRAL = codes('GT BZ SV HN NI CR PA CU DO HT JM TT BS BB PR AG DM GD KN LC VC');
const SOUTH_AMERICA = codes('AR BO BR CL CO EC GY PY PE SR UY VE');
const LATIN_AMERICA = codes('MX GT SV HN NI CR PA CU DO PR AR BO BR CL CO EC PY PE UY VE');
const APAC = codes('AU NZ JP KR CN HK TW MO SG MY TH VN PH ID IN PK BD LK NP MM KH LA MN BN FJ PG');

const names = (list) => [...new Set(list.map(fromCode).filter(Boolean))].sort((a, b) => a.localeCompare(b));

const regions = {
  europe: names(EUROPE),
  emea: names([...EUROPE, ...MIDDLE_EAST, ...AFRICA]),
  americas: names([...NORTH_AMERICA, ...CARIBBEAN_CENTRAL, ...SOUTH_AMERICA]),
  'north-america': names(NORTH_AMERICA),
  'latin-america': names(LATIN_AMERICA),
  'south-america': names(SOUTH_AMERICA),
  apac: names(APAC),
};

// Every canonical country name, for the location picker.
const all = new Set();
for (let a = 65; a <= 90; a++) for (let b = 65; b <= 90; b++) {
  const n = fromCode(String.fromCharCode(a, b));
  if (n) all.add(n);
}
const countries = [...all].sort((a, b) => a.localeCompare(b));

const arr = (list) => '[\n' + list.map((n) => `    ${JSON.stringify(n)},`).join('\n') + '\n  ]';
const out = `/**
 * Countries and the regions job postings name.
 *
 * GENERATED by scripts/update/gen-regions.mjs — do not edit by hand. The names
 * come from the same Intl data the update pipeline used to write every
 * \`country\` and \`workplace.where\` in the dataset, and are frozen here as
 * constants rather than recomputed in the browser: a browser's ICU can name a
 * handful of countries differently, and a region that silently failed to
 * contain a country would drop its roles from a search without any sign.
 *
 * Membership is deliberately the common hiring reading rather than strict
 * geography — "Europe" in a job posting does not usually mean Russia.
 */

export type RegionKey =
  | 'worldwide'
  | 'europe'
  | 'emea'
  | 'americas'
  | 'north-america'
  | 'latin-america'
  | 'south-america'
  | 'apac';

export const REGION_LABELS: Record<RegionKey, string> = {
  worldwide: 'Worldwide',
  europe: 'Europe',
  emea: 'EMEA',
  americas: 'the Americas',
  'north-america': 'North America',
  'latin-america': 'Latin America',
  'south-america': 'South America',
  apac: 'Asia-Pacific',
};

/** Every canonical country name, alphabetical. */
export const COUNTRIES: readonly string[] = ${arr(countries)};

const MEMBERS: Record<Exclude<RegionKey, 'worldwide'>, readonly string[]> = {
${Object.entries(regions).map(([k, v]) => `  ${JSON.stringify(k)}: ${arr(v).replace(/\n {4}/g, '\n    ')},`).join('\n')}
};

const MEMBER_SETS = new Map<string, ReadonlySet<string>>(
  Object.entries(MEMBERS).map(([key, list]) => [key, new Set(list)]),
);

export function isRegionKey(value: string): value is RegionKey {
  return value === 'worldwide' || MEMBER_SETS.has(value);
}

/**
 * Whether a posting's \`where\` covers someone in \`country\`.
 *
 * \`worldwide\` covers everyone; a country covers itself; a region covers its
 * members. An empty \`where\` covers nobody — it means the posting did not say,
 * and the caller treats that as unknown rather than as a match.
 */
export function covers(where: readonly string[], country: string): boolean {
  for (const entry of where) {
    if (entry === 'worldwide' || entry === country) return true;
    if (MEMBER_SETS.get(entry)?.has(country) === true) return true;
  }
  return false;
}

/**
 * A company-level region label ("Europe", "Global", "United States") in the
 * vocabulary \`where\` uses. Company records predate the slot format and store
 * readable names; this is the one place they are translated.
 */
export function regionFromLabel(label: string): string | null {
  const key = label.trim().toLowerCase();
  if (key === '') return null;
  if (key === 'global' || key === 'worldwide' || key === 'anywhere') return 'worldwide';
  if (key === 'europe' || key === 'eu' || key === 'european union') return 'europe';
  if (key === 'emea') return 'emea';
  if (key === 'americas' || key === 'the americas' || key === 'amer') return 'americas';
  if (key === 'north america') return 'north-america';
  if (key === 'latin america' || key === 'latam') return 'latin-america';
  if (key === 'south america') return 'south-america';
  if (key === 'apac' || key === 'asia' || key === 'asia-pacific' || key === 'asia pacific') return 'apac';
  const country = COUNTRIES.find((name) => name.toLowerCase() === key);
  return country ?? null;
}
`;
writeFileSync(new URL('../../src/lib/regions.ts', import.meta.url), out);
console.log('countries:', countries.length);
for (const [k, v] of Object.entries(regions)) console.log('  ' + k.padEnd(15) + v.length);
